// Test data for development and testing
export const testData = {
  info: {
    APPID: 90272,
    ID_NUM: 118741,
    NAME_FORMAT: "F",
    LAST_NAME: "TAKI",
    FIRST_NAME: "Salma",
    MIDDLE_NAME: null,
    BIRTH_NAME: "BJ476811",
    MOBILE_PHONE: "635870672",
    EMAIL_ADDRESS: "118741@aui.ma",
    STUD_MSTR_EMPLOY: "E"
  },
  candidacy: [
    {
      ID_NUM: 118741,
      YR_CDE: "2223",
      DIV_CDE: "UG",
      STAGE: "ENR",
      PROG_CDE: "BBA",
      TRM_CDE: "FA",
      Bac_year: "2022",
      HIGH_SCHOOL: "47508",
      High_school_diploma: "1",
      High_School_distinction: "T",
      HS_Org_Type_AD: "HS",
      gpa: 16.54,
      total_ap_credits: 15,
      total_inst_credits: 16,
      CL_Org_Type_AD: null,
      CL_GPA: null,
      CL_Total_AP_Credits: null,
      CL_Total_Inst_Credits: null,
      school_type: null,
      udef_1a_1: "H",
      ACt: null,
      GAT: null,
      GRE: null,
      SAT: null,
      SATRC: null,
      SATWC: null,
      TEF: null,
      TOEPP: null,
      birth_dte: "2004-10-19T00:00:00.000+00:00",
      citizen_of: "MA",
      CITY: "CASABLANCA",
      COUNTRY: "MA",
      ADDR_LINE_1: "RES AL FADL GH 4 IMM 1 NR 4",
      BIRTH_NAME: "BJ476811",
      FIRST_NAME: "Salma",
      LAST_NAME: "TAKI",
      EMAIL_ADDRESS: "118741@aui.ma",
      gender: "F",
      mobile: "635870672",
      Father_address: null,
      Mother_address: null,
      Father_Phone: null,
      Mother_Phone: null,
      Father_Occupation: null,
      Mother_Occupation: null,
      app_fee_dte: "2021-12-27T23:00:00.000+00:00"
    }
  ],
  student: {
    IDNUM: 118741,
    Stud_employ_cde: "E",
    web_grp: "07",
    tuition_cde: "RG",
    ENTRANCE_YR: "2223",
    ENTRANCE_TRM: "FA",
    CURRENT_CLASS_CDE: "JR",
    NUM_OF_CRS: 4,
    HRS_ENROLLED: 12,
    TRM_HRS_EARNED: 0,
    CAREER_GPA: 2.68,
    DEGR_CDE: "BS",
    MAJOR_1: "CSC",
    MINOR_1: null,
    CONCENTRATION_1: null
  }
}; 